baseurl: "/"
languageCode: "en-us"
title: "zach blake"
theme: "xmin"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles:
  ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: Posts
      url: "post/"
      weight: 2
    - name: Tags
      url: "tags/"
      weight: 3

params:
  description: "My personal website with my portfolio and some blog posts"
  footer: "&copy; [Zach Blake](https://twitter.com/heyztb) {Year} | [Github](https://github.com/heyztb) | [Twitter](https://twitter.com/heyztb)"

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
